In [1]:
"""
created on Mar 21 2019

@author: Huan Zheng
"""
#  Maxout网络实现mnist分类

'\ncreated on Mar 21 2019\n\n@author: Huan Zheng\n'

In [1]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/")

print ('输入数据:',mnist.train.images)
print ('输入数据打shape:',mnist.train.images.shape)

import pylab 
im = mnist.train.images[1]
im = im.reshape(-1,28)
pylab.imshow(im)
pylab.show()


print ('输入数据打shape:',mnist.test.images.shape)
print ('输入数据打shape:',mnist.validation.images.shape)


import tensorflow as tf #导入tensorflow库

tf.reset_default_graph()
# tf Graph Input
x = tf.placeholder(tf.float32, [None, 784]) # mnist data维度 28*28=784
y = tf.placeholder(tf.int32, [None]) # 0-9 数字=> 10 classes

# Set model weights
W = tf.Variable(tf.random_normal([784, 10]))
b = tf.Variable(tf.zeros([10]))


z= tf.matmul(x, W) + b


maxout = tf.reduce_max(z,axis= 1,keep_dims=True)
# Set model weights
W2 = tf.Variable(tf.truncated_normal([1, 10], stddev=0.1))
b2 = tf.Variable(tf.zeros([1]))
# 构建模型
pred = tf.nn.softmax(tf.matmul(maxout, W2) + b2)

# 构建模型
#pred = tf.nn.softmax(z) # Softmax分类

# Minimize error using cross entropy
#cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(pred), reduction_indices=1))
cost = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(labels=y, logits=z))
#参数设置
learning_rate = 0.04
# 使用梯度下降优化器
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

training_epochs = 200
batch_size = 512
display_step = 1


# 启动session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())# Initializing OP

    # 启动循环开始训练
    for epoch in range(training_epochs):
        avg_cost = 0.
        total_batch = int(mnist.train.num_examples/batch_size)
        # 遍历全部数据集
        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            # Run optimization op (backprop) and cost op (to get loss value)
            _, c = sess.run([optimizer, cost], feed_dict={x: batch_xs,
                                                          y: batch_ys})
            # Compute average loss
            avg_cost += c / total_batch
        # 显示训练中的详细信息
        if (epoch+1) % display_step == 0:
            print ("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(avg_cost))

    print( " Finished!")

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
输入数据: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
输入数据打shape: (55000, 784)


<Figure size 640x480 with 1 Axes>

输入数据打shape: (10000, 784)
输入数据打shape: (5000, 784)
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Epoch: 0001 cost= 8.686317849
Epoch: 0002 cost= 5.081104004
Epoch: 0003 cost= 3.528971483
Epoch: 0004 cost= 2.770142865
Epoch: 0005 cost= 2.335227616
Epoch: 0006 cost= 2.058597384
Epoch: 0007 cost= 1.861966521
Epoch: 0008 cost= 1.718341188
Epoch: 0009 cost= 1.609431707
Epoch: 0010 cost= 1.510685237
Epoch: 0011 cost= 1.446474160
Epoch: 0012 cost= 1.372665485
Epoch: 0013 cost= 1.329426361
Epoch: 0014 cost= 1.270361591
Epoch: 0015 cost= 1.240461773
Epoch: 0016 cost= 1.196306167
Epoch: 0017 cost= 1.168428530
Epoch: 0018 cost= 1.139284244
Epoch: 0019 cost= 1.105367563
Epoch: 0020 cost= 1.089031187
Epoch: 0021 cost= 1.056769997
Epoch: 0022 cost= 1.043813117
Epoch: 0023 cost= 1.020677343
Epoch: 0024 cost= 1.004754967
Epoch: 0025 cost= 0.980897794
Epoch: 0026 cost= 0.969481140
Epoch: 0027 cost= 0.949793940
Epoch: 0028 cost= 0.942471172
Epoch: 0029 cost= 0.924782541
Epoch: 0