In [1]:
"""
areated on 12 Feb 2019

@author: Super Huan
"""
# 深度学习框架Tensorflow

'\nareated on 12 Feb 2019\n\n@author: Super Huan\n'

In [4]:
import tensorflow as tf
a = 3
# Created a variable
w = tf.Variable([[0.5, 1.0]])
x = tf.Variable([[2.0], [1.0]])
y = tf.matmul(w, x) # 矩阵乘法
print('w = ', w, '\nx = ', x, '\ny = ', y)
# variables have to be explicitly initialized before you can run Ops
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(y.eval())

w =  <tf.Variable 'Variable_4:0' shape=(1, 2) dtype=float32_ref> 
x =  <tf.Variable 'Variable_5:0' shape=(2, 1) dtype=float32_ref> 
y =  Tensor("MatMul_2:0", shape=(1, 1), dtype=float32)
[[2.]]


In [ ]:
tf.zeros([3, 4], int32) ==> [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

# 'tensor' is [[1, 2, 3], [4, 5, 6]]
tf,zeros_like(tensor) ==> [[0, 0, 0], [0, 0, 0]]
tf,ones_like(tensor) ==> [[1, 1, 1], [1, 1, 1]]

# constant variable
tensor = tf.constant([, 2, 3, 4, 5, 6]) ==> [1  2 3 4 5 6]

In [6]:
norm = tf.random_normal([2, 3], mean=1, stddev=4)

c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)

sess = tf.Session()
print(sess.run(norm))
print(sess.run(shuff))


[[10.079887  -1.8654385  1.015763 ]
 [ 9.547961   1.3891243  4.269678 ]]
[[3 4]
 [5 6]
 [1 2]]


In [7]:
state = tf.Variable(0)
new_value = tf.add(state, tf.constant(1)) # tensorflow下:+1
update = tf.assign(state, new_value) # 将 new_value 的值赋给 state

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


In [12]:
import numpy as np
a = np.zeros((3, 4))
ta = tf.convert_to_tensor(a)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(ta))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
